import Head from 'next/head'
import { useEffect, useState } from 'react';
import GitHubLogInButton from '../components/GitHubLogInButton'
import { logInGitHub, logOut, onAuthStateChange } from '../firebase/client';
import styles from '../styles/Home.module.css'

export default function Home() {

  const [ user, setUser ] = useState(null);

  useEffect(() => {
    onAuthStateChange(setUser);
  }, []);

  //GitHub Log In function
  const onClickHandlerLogIn = () => {
    logInGitHub()
        // .then((data) => {
        //     console.log('Desde el botón recibo esta info: ', data);
        //     !(typeof data === 'string') && setUser({
        //       name: data.displayName,
        //       email: data.email,
        //       photoURL: data.photoURL,
        //     })
        // })
        .catch((error) => {
            console.log('An error has occurred: ', error);
        });
  };

  const onClickHandlerLogOut = () => {
    setUser(null);
    logOut();
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Twitfake</title>
        <meta name="description" content="Generated by create next app" />
        {/* cambiar lo de arriba para que, cuando se vea en un resultado de Google, la 
        descripción sea 'buena' */}
        <link rel="icon" href="/twitfake.ico" />
      </Head>

      <section className={styles.mainSection}>
        <main className={styles.main}>
        <div className={styles.iconContainer}>
          <img src='/twitfake.png' alt='img' className={styles.iconImg}></img>
        </div>
          <h1>
            Twitfake
          </h1>
          <h2>Talk about development <br />
          with other developers!</h2>

        {/* If user is not Logged In, the Log In buttons are going to be shown */}
          {
            !user ? <div className={styles.buttonContainer}>
            <GitHubLogInButton onClickHandler={onClickHandlerLogIn} />
          </div> :
          <div>
            <img src={user.photoURL} alt='img not found' style={{height: '300px'}}/>
            <h3>{user.name}</h3>
            <p>{user.email}</p>
            <button onClick={onClickHandlerLogOut}>Log out</button>
          </div>
          }
          
        </main>
      </section>

    </div>
  )
}
